# Generated by Django 5.0.6 on 2024-06-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupomusical',
            options={'verbose_name': 'Grupo musical', 'verbose_name_plural': 'Grupos musicales'},
        ),
    ]
