# Generated by Django 5.0.6 on 2024-06-10 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0003_author_grupomusical_my_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomusical',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rock.author'),
        ),
    ]
